require 'jekyll'

task :up do
  puts "Activating and launching jekyll server..."
  pid = %x['jekyll --server & ']
  puts pid
end

task :ready_for_the_day => [:turn_off_alarm, :groom_myself, :make_coffee, :walk_dog] do
  puts "Ready for the day!"
end